.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. paycheckcash_qt test_paycheckcash_qt
clean: FORCE
	$(MAKE) -C .. paycheckcash_qt_clean test_paycheckcash_qt_clean
check: FORCE
	$(MAKE) -C .. test_paycheckcash_qt_check
paycheckcash-qt paycheckcash-qt.exe: FORCE
	 $(MAKE) -C .. paycheckcash_qt
